apiVersion: v1
kind: Service
metadata:
  name: ossintel-service
spec:
  ports:
    - port: 80
      targetPort: 8001
      protocol: TCP
      name: http
  selector:
    app: ossintel
  type: LoadBalancer
  loadBalancerSourceRanges: []  